### ISSUE TITLE
how to run this code?

### ISSUE THREAD

**Issue by vicLzs** [rorlandoc/abaqus_cpp_usubs#1]
how to run this code?

**Comment by rorlandoc** [comment]
Will you need access to an [Abaqus installation](https://www.3ds.com/products-services/simulia/products/abaqus/). If you have access to one you should be able to run this demo with
```bash
abaqus interactive job=your_job_name input=user.inp user=user.cpp
``` 

If this does not work, you may have to install Visual Studio Community (on windows) or GCC (on linux) and Intel oneAPI and link them with Abaqus. Some good resources exist online already to get started (for example: [this one](https://www.researchgate.net/publication/357113774_Linking_Abaqus_2021_Intel_oneAPI_Fortran_Compiler_Visual_Studio_2019_in_Windows_10_x64) and [this one](https://www.linkedin.com/pulse/abaqus-intel-compilers-linux-marcin-wierszycki?trk=pulse-article)).
